apiVersion: v1
kind: Pod
metadata:
  name: k8s-training
  labels:
    name: k8s-training
spec:
  containers:
  - name: hello-world-server
    image: unheardof77/k8s-training:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3001
